scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: fluentbit
  scrape_interval: 5s
  static_configs:
  - targets:
    - fluentbit:2021
- job_name: process-exporter
  scrape_interval: 5s
  static_configs:
  - targets:
      - process-exporter:9256